modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="therage"
version="1.0alpha"
displayName="The Rage"
authors="Gamerofpro"
description='''
A horror survival mod where a mysterious force known as The Rage slowly corrupts the world. As the corruption spreads, terrifying events, hostile creatures, and unexplained phenomena make survival increasingly difficult.
'''
logoFile="logo.png"

[[dependencies.therage]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.therage]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"
